### ISSUE TITLE
Suggestion worldguard addition

### ISSUE THREAD

**Issue by LuckserSky34** [xF3d33/TimeBlockEraser#1]
Add support for worldguard regions, so the players can only place timed blocks in a specific region listed in config.yml or adding a custom flag like: time-block-eraser allow.

**Comment by xF3d33** [comment]
Hello, thanks for the suggestion, I'm gonna add this in the next commit

**Comment by xF3d33** [comment]
Hello, can you try the latest alpha build on modrinth and check if it does work?
